#!/bin/sh
#
# Extract git-log and put them into Elasticsearch
# Usage:
#   ./git-log2es <git-dir>
#

IDX_TYPE=$(basename $1)
IDX_NAME="oss-gitlog"
ES_PATH="http://localhost:9200"
STREAM2ES=./stream2es

mkdir -p bulk
./git-esbulk.sh $1 > bulk/$IDX_TYPE.json
./create-index.sh $IDX_TYPE $IDX_NAME $ES_PATH
$STREAM2ES stdin --target $ES_PATH/$IDX_NAME/$IDX_TYPE < bulk/$IDX_TYPE.json
